spring:
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format-sql: true
#    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/springdb_test
    username: root
    password: $cursedbanana2212
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 6060

